baseURL: https://chaogong.netlify.app/
languageCode: en-us
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
title: GongChao
theme: GongChao
footnotereturnlinkcontents: ↩
enableRobotsTXT: yes
permalinks:
  cn: /cn/:year/:month/:day/:slug/
  en: /en/:year/:month/:day/:slug/
  posts: /posts/:year/:month/:day/:slug/
menu:
  cn:
    - name: 关于
      url: /cn/about/
      weight: 1
    - name: 日志
      url: /cn/posts/
      weight: 2
    - name: English
      url: /
      weight: 4
  en:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /en/about/
      weight: 2
    - name: Research
      url: /en/posts/
      weight: 3
    - name: 中文
      url: /cn/posts/
      weight: 4
params:
  GithubRepo: https://github.com/GongChao-PKU/chaogong/
  GithubEdit: https://github.com/GongChao-PKU/chaogong/tree/main/content/
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  blogDirName: posts
  copyright: '&copy;'
  copyrightYear: 2023-{Year}
  defaultLang: en
  description: Peronal website of Chao Gong
  favicon: https://simpleicons.org/icons/matrix.svg
  homeText: You just need a Hugo blog from scratch
  lang:
    Sitelastupdate:
      cn: 最近一次更新于
      en: Site last updated on
    author:
      cn: 巩超
      en: Chao Gong
    edit:
      cn: 编辑本页
      en: Suggest an edit of this page
    lastupdate:
      cn: 最后一次修改于
      en: Last modified on
    license:
      cn: 版权
      en: License
    madeWith:
      cn: 本站驱动
      en: Made with
    sourceCode:
      cn: 积盒
      en: Github
    subscribe:
      cn: 订阅
      en: Subscribe
    weibo:
      cn: 微博
      en: Weibo  
  logo:
    alt: GongChao
    height: 50
    url: https://simpleicons.org/icons/matrix.svg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: no
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    parser:
      attribute: yes
      autoHeadingID: yes
    renderer:
      hardWraps: no
      unsafe: yes
      xHTML: no
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: yes
    noClasses: yes
    style: pygments
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: yes
    startLevel: 2
imaging:
  quality: 100
